Aplicacao/urls.py
from django.urls import path
from . import views

app_name = 'aplicacao'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('adicionar/', views.AddView.as_view(), name="add"),
]

Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicacao.urls')),
]

Aplicacao/models.py
from django.db import models

class Pokemon(models.Model):
    nome = models.CharField(max_length=100)
    tipo1 = models.CharField(max_length=50)
    tipo2 = models.CharField(max_length=50, blank=True, null=True)
    hp = models.IntegerField()
    altura = models.DecimalField(max_digits=5, decimal_places=2)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    descricao = models.TextField()
    imagem = models.URLField(max_length=200)

Aplicacao/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Pokemon

class HomeView(View):
    def get(self, request):
        return render(request, 'home.html')

class AddView(View):
    def get(self, request): 
        return render(request, 'adicionar.html')
    
    def post(self, request):
        name = request.POST.get("nome")
        tipo1 = request.POST.get("tipo1")
        tipo2 = request.POST.get("tipo2")
        hp = request.POST.get("hp")
        altura = request.POST.get("altura")
        peso = request.POST.get("peso")
        urlImagem = request.POST.get("imagem")
        descricao = request.POST.get("descricao")

        pokemon = Pokemon(
            nome=name,
            tipo1 = tipo1,
            tipo2 = tipo2,
            hp = hp,
            altura = altura,
            peso = peso,
            descricao = descricao,
            imagem = urlImagem
        )

        pokemon.save()

        return redirect('aplicacao:home')
        

Aplicacao/templates/adicionar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://static.wikia.nocookie.net/pokemon-fano/images/6/6f/Poke_Ball.png/revision/latest?cb=20140520015336" type="image/x-icon">
    <title>PokéDex - Adicionar</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'adicionar.css' %}">
</head>
<body>
    <main>
        <h1>Adicionar Pokémon</h1>
        <form action="{% url 'aplicacao:add' %}" method="POST">
            {% csrf_token %}
            
            <div class="inputdiv">
                <label for="nome">Nome*:</label>
                <input type="text" name="nome" id="nome" placeholder="Digite o nome" required>
            </div>
            
            <div class="inputdiv">
                <label for="tipo1">Tipo 1*:</label>
                <select name="tipo1" id="tipo1" required>
                    <option value="">-- Selecione o Tipo 1 --</option>
                    <option value="Normal">Normal</option>
                    <option value="Fogo">Fogo</option>
                    <option value="Água">Água</option>
                    <option value="Elétrico">Elétrico</option>
                    <option value="Planta">Planta</option>
                    <option value="Gelo">Gelo</option>
                    <option value="Lutador">Lutador</option>
                    <option value="Venenoso">Venenoso</option>
                    <option value="Terrestre">Terrestre</option>
                    <option value="Voador">Voador</option>
                    <option value="Psíquico">Psíquico</option>
                    <option value="Inseto">Inseto</option>
                    <option value="Pedra">Pedra</option>
                    <option value="Fantasma">Fantasma</option>
                    <option value="Dragão">Dragão</option>
                    <option value="Sombrio">Sombrio</option>
                    <option value="Aço">Aço</option>
                    <option value="Fada">Fada</option>
                </select>
            </div>
            
            <div class="inputdiv">
                <label for="tipo2">Tipo 2:</label>
                <select name="tipo2" id="tipo2">
                    <option value="">-- Selecione o Tipo 2 (Opcional) --</option>
                    <option value="Normal">Normal</option>
                    <option value="Fogo">Fogo</option>
                    <option value="Água">Água</option>
                    <option value="Elétrico">Elétrico</option>
                    <option value="Planta">Planta</option>
                    <option value="Gelo">Gelo</option>
                    <option value="Lutador">Lutador</option>
                    <option value="Venenoso">Venenoso</option>
                    <option value="Terrestre">Terrestre</option>
                    <option value="Voador">Voador</option>
                    <option value="Psíquico">Psíquico</option>
                    <option value="Inseto">Inseto</option>
                    <option value="Pedra">Pedra</option>
                    <option value="Fantasma">Fantasma</option>
                    <option value="Dragão">Dragão</option>
                    <option value="Sombrio">Sombrio</option>
                    <option value="Aço">Aço</option>
                    <option value="Fada">Fada</option>
                </select>
            </div>
        
            <div class="inputdiv">
                <label for="hp">Pontos de Vida*:</label>
                <input type="number" name="hp" id="hp" min="1" placeholder="Digite o HP" required>
            </div>
            
            <div class="inputdiv">
                <label for="altura">Altura(m)*:</label>
                <input type="number" name="altura" id="altura" step="0.01" placeholder="Digite a altura" required>
            </div>
            
            <div class="inputdiv">
                <label for="peso">Peso(kg)*:</label>
                <input type="number" name="peso" id="peso" step="0.01" placeholder="Digite o peso" required>
            </div>
            
            <div class="inputdiv">
                <label for="imagem">URL da Imagem*:</label>
                <input type="url" name="imagem" id="imagem" placeholder="Digite a URL da imagem" required>
            </div>

            <div class="inputdiv" id="txtArea">
                <label for="descricao">Descrição*:</label>
                <textarea name="descricao" id="descricao" rows="4"  required></textarea>
            </div>
        
            <div>
                <button type="submit">ADICIONAR</button>
            </div>
        </form>
        
    </main>
</body>
</html>

Aplicacao/templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://static.wikia.nocookie.net/pokemon-fano/images/6/6f/Poke_Ball.png/revision/latest?cb=20140520015336" type="image/x-icon">
    <title>PokéDex</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% load static %} 
    <link rel="stylesheet" href="{% static 'home.css' %}">
</head>
<body>
    <header>
        <img src="https://archives.bulbagarden.net/media/upload/4/4b/Pok%C3%A9dex_logo.png" alt="PokéDex logo">
    </header>
    <main>
        <a href="{% url 'aplicacao:add' %}">
            <div class="card" id="add">
                <h2>Adicionar Pokémon</h2>
                <span><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-plus"><path d="M5 12h14"/><path d="M12 5v14"/></svg></span>
            </div>
        </a>
        <div class="card" id="list">
            <h2>Ver Pokémon</h2>
            <span><svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-eye"><path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></svg></span>
        </div>
    </main>
</body>
</html>